<a href="https://colab.research.google.com/github/smdr111/data_preparation/blob/main/data_preparation_final_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#11-modul. Maʼlumotlarga ishlov berish. Maʼlumotlarni tayyorlash
# 11.28. Modul boʻyicha yakuniy amaliy vazifa

**Bu vazifalarni bajargach, maʼlumotlarni yuklash, tozalash, oʻzgartirish, matnlarni normalizatsiya qilish, qiymatlarni tekshirish, guruhlash va tahlil qilish kabi maʼlumotlarga ishlov berish (data processing) koʻnikmalarini egallaysiz.**

#**Umumiy maʼlumotlar bilan ishlash**

#Dataset haqida qisqacha maʼlumot
Restoran savdosi boʻyicha maʼlumotlar toʻplami 17 534 tranzaksiya uchun maʼlumotlarni oʻz ichiga oladi. Maʼlumotlar yetishmayotgan yoki baʼzilari toʻliq kiritilmagan boʻlishi mumkin. Maʼlumotlar toʻplamida asosiy taomlar, shirinliklar, ichimliklar kabi bir nechta toifadagi savdo tafsilotlari mavjud.


 0.   **Unnamed 0** – indekslarni;
 1.   **Order ID** – buyurtma IDʼsini;
 2.   **Customer ID** – mijoz IDʼsini;
 3.   **Category** – mahsulotlar kategoriyasini;
 4.   **Item** – mahsulot nomini;
 5.   **Price** – mahsulotning narxini;
 6.   **Quantity** – qancha mahsulot sotilgani miqdorini;
 7.   **Order Total** – umumiy narx qancha ekanini;
 8.   **Order Date** – buyurtma berilgan sanani (vaqt);
 9.   **Payment Method** – toʻlov usuli turini saqlaydi.

#1) Quyida berilgan datasetni yuklab olib, ustun nomlarini koʻring va ularni maʼno jihatdan tushunarli shaklga keltiring. `Unnamed: 0` ustunini tashlab yuboring!

In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/restaurant_sales.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [ ]:
#javobni shu yerda yozing
df.drop(columns=['Unnamed: 0'],inplace=True)

In [ ]:
df.head()

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

#2) Maʼlumotlarning umumiy holatini (info(), describe()) tekshiring.

In [ ]:
#javobni shu yerda yozing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        17534 non-null  object
 1   Customer ID     17534 non-null  object
 2   Category        17498 non-null  object
 3   Item            15776 non-null  object
 4   Price           17534 non-null  float64
 5   Quantity        17104 non-null  float64
 6   Order Total     17104 non-null  float64
 7   Order Date      17534 non-null  object
 8   Payment Method  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

In [ ]:
df.describe()

              Price      Quantity   Order Total
count  17534.000000  17104.000000  17104.000000
mean       6.207312      3.014149     19.914494
std        4.993782      1.414598     18.732549
min       -1.000000      1.000000      1.000000
25%        3.000000      2.000000      7.500000
50%        5.000000      3.000000     15.000000
75%        7.000000      4.000000     25.000000
max       20.000000      5.000000    100.000000

#3) Har bir ustundagi boʻsh qiymatlarni aniqlang va ularni toʻldirish strategiyasini ishlab chiqing.

In [ ]:
#javobni shu yerda yozing
df.isnull().sum()

Order ID             0
Customer ID          0
Category            36
Item              1758
Price                0
Quantity           430
Order Total        430
Order Date           0
Payment Method    1082
dtype: int64

In [ ]:
df.Price.replace(-1,np.nan,inplace=True)

/tmp/ipython-input-1932045744.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Price.replace(-1,np.nan,inplace=True)

In [ ]:
grps=df.groupby('Category').Price.mean().round()
for idx in grps.index:
  df[df.Category==idx]=df[df.Category==idx].fillna({'Price':grps[idx]})

In [ ]:
df[df.Price.isnull()]

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
3000,ORD_528695,CUST_068,NaN,NaN,NaN,NaN,NaN,2022-05-01,NaN
10500,ORD_402838,CUST_023,NaN,NaN,NaN,NaN,NaN,2022-01-20,Cash
15500,ORD_810133,CUST_025,NaN,NaN,NaN,NaN,NaN,2022-09-30,NaN
17000,ORD_666259,CUST_013,NaN,NaN,NaN,5.0,25.0,2022-10-04,NaN

In [ ]:
df.dropna(subset=['Price'],inplace=True)
df.isnull().sum()

Order ID             0
Customer ID          0
Category            32
Item              1754
Price                0
Quantity           427
Order Total        427
Order Date           0
Payment Method    1079
dtype: int64

In [ ]:
df['Payment Method'].fillna(method='ffill',inplace=True)

/tmp/ipython-input-3862034346.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment Method'].fillna(method='ffill',inplace=True)
/tmp/ipython-input-3862034346.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Payment Method'].fillna(method='ffill',inplace=True)

In [ ]:
ctg=dict(zip(df.Price,df.Category))
df.Category=df.Category.fillna(df.Price.map(ctg))

In [ ]:
df.isnull().sum()

Order ID             0
Customer ID          0
Category             0
Item              1754
Price                0
Quantity           427
Order Total        427
Order Date           0
Payment Method       0
dtype: int64

In [ ]:
item=dict(zip(df.Price,df.Item))
df.Item=df.Item.fillna(df.Price.map(item))

In [ ]:
df.dropna(subset=['Item'],inplace=True)

In [ ]:
df.isnull().sum()

Order ID            0
Customer ID         0
Category            0
Item                0
Price               0
Quantity          248
Order Total       248
Order Date          0
Payment Method      0
dtype: int64

In [ ]:
df.Quantity.fillna(method='ffill',inplace=True)

/tmp/ipython-input-3265646807.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Quantity.fillna(method='ffill',inplace=True)
/tmp/ipython-input-3265646807.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.Quantity.fillna(method='ffill',inplace=True)

In [ ]:
df['Order Total'].fillna(df.Price*df.Quantity,inplace=True)

/tmp/ipython-input-4038026821.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order Total'].fillna(df.Price*df.Quantity,inplace=True)

In [ ]:
df.isnull().sum()

Order ID          0
Customer ID       0
Category          0
Item              0
Price             0
Quantity          0
Order Total       0
Order Date        0
Payment Method    0
dtype: int64

#4) Har bir ustundagi takroriy qiymatlarni toping va ularga qanday oʻzgartirish kiritish kerakligini hal qiling.

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#javobni shu yerda yozing
for col in df.columns:
     print(df.duplicated(col).value_counts())

False    17080
Name: count, dtype: int64
True     16980
False      100
Name: count, dtype: int64
True     17075
False        5
Name: count, dtype: int64
True     16904
False      176
Name: count, dtype: int64
True     17066
False       14
Name: count, dtype: int64
True     17075
False        5
Name: count, dtype: int64
True     17039
False       41
Name: count, dtype: int64
True     16350
False      730
Name: count, dtype: int64
True     17077
False        3
Name: count, dtype: int64

#5) Maʼlumotlar toʻplamidagi noto‘g‘ri maʼlumotlar (masalan, son turishi kerak bo‘lgan ustunda matn bo‘lsa) mavjudligini tekshiring va to‘g‘rilang.

In [ ]:
#javobni shu yerda yozing
# mening fikrimcha bu datasetda har bir ustunda to`g`ri
# shaklda ma`lumot berilgan(son ustunida son,matn ustunida matn)
df.Quantity=df.Quantity.astype(int)

In [ ]:
df

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,side salad#?,3.0,1,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60.0,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90.0,2022-07-20,Digital Wallet
...,...,...,...,...,...,...,...,...,...
17527,ORD_223096,CUST_088,Side Dishes,Garlic Bread,4.0,3,12.0,2022-04-06,Credit Card
17528,ORD_721774,CUST_006,Side Dishes,Mashed Potatoes,4.0,5,20.0,2022-04-22,Digital Wallet
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2,8.0,2022-01-27,Digital Wallet

#6) Maʼlumotlar toʻplamidagi **katta/kichik harf** muammolari boʻlgan joylarni toping va bir xil formatga keltiring.

In [ ]:
#javobni shu yerda yozing
df.Item=df.Item.str.title()

In [ ]:
df

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad#?,3.0,1,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60.0,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90.0,2022-07-20,Digital Wallet
...,...,...,...,...,...,...,...,...,...
17527,ORD_223096,CUST_088,Side Dishes,Garlic Bread,4.0,3,12.0,2022-04-06,Credit Card
17528,ORD_721774,CUST_006,Side Dishes,Mashed Potatoes,4.0,5,20.0,2022-04-22,Digital Wallet
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2,8.0,2022-01-27,Digital Wallet

#7) Maʼlumotlar turini oʻzgartirish.
 * Ustunlarning maʼlumot turlarini tekshiring. Notoʻgʻri turlarga ega boʻlgan ustunlarni toʻgʻri formatga oʻtkazing.
 * `order_date` yoki unga oʻxshash ustunni datetime formatiga oʻtkazing.

In [ ]:
import datetime as dt

In [ ]:
#javobni shu yerda yozing
df[['Order Date']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 17080 entries, 0 to 17532
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  17080 non-null  object
dtypes: object(1)
memory usage: 782.9+ KB

In [ ]:
df[['Order Date']].head()

   Order Date
0  2023-12-21
1  2023-05-19
2  2023-09-27
4  2022-05-15
5  2022-07-20

In [ ]:
pd.to_datetime(df['Order Date'])

0       2023-12-21
1       2023-05-19
2       2023-09-27
4       2022-05-15
5       2022-07-20
           ...
17527   2022-04-06
17528   2022-04-22
17530   2023-12-18
17531   2022-05-20
17532   2022-01-27
Name: Order Date, Length: 17080, dtype: datetime64[ns]

#8) Mahsulot nomlarida noto‘g‘ri yoki nomaʼlum belgilar (?, NaN, #) mavjudligini tekshiring va ularni tuzating.

In [ ]:
#javobni shu yerda yozing
df.Item.value_counts().index

Index(['Chocolate Cake', 'Ice Cream', 'Side Salad', 'Mashed Potatoes',
       'Pasta Alfredo', 'Water (0.5)', 'French Fries', 'Grilled Chicken',
       'Coca Cola', 'Cheese Fries', 'Steak', 'Orange Juice',
       'Grilled Vegetables', 'Cheesecake', 'Lemonade', 'Sweet Potato Fries',
       'Beef Chili', 'Brownie', 'Chicken Melt', 'Fruit Salad', 'Salmon',
       'Garlic Bread', 'Iced Tea', 'Vegetarian Platter', 'Onion Rings',
       'Nachos Grande', 'Water', 'Vegetarian Platter#', 'Grilled Chicken?',
       'Cheese Fries?', 'French Fries#', 'Chicken Melt?', 'Pasta Alfredo?',
       'Ice Cream#', 'Coca Cola?', 'Coca Cola#', 'Fruit Salad?', 'Water#',
       'Water?', 'Pasta Alfredo#', 'Beef Chili#', 'Grilled Chicken#',
       'Side Salad?', 'Brownie?', 'Steak#', 'Sweet Potato Fries?',
       'Side Salad#', 'Mashed Potatoes?', 'Chocolate Cake#', 'Orange Juice?',
       'Salmon#', 'Grilled Vegetables#', 'Ice Cream?', 'Cheesecake?',
       'Brownie#', 'Lemonade (1.0)', 'Garlic Bread?', 'Cheese Fries#',
       'Mashed Potatoes#', 'Salmon?', 'Chicken Melt#', 'Garlic Bread#',
       'Iced Tea?', 'Vegetarian Platter?', 'Grilled Vegetables?',
       'Beef Chili?', 'Lemonade?', 'Steak?', 'Sweet Potato Fries#',
       'Fruit Salad#', 'Orange Juice#', 'French Fries?', 'Onion Rings#',
       'Nachos Grande#', 'Nachos Grande?', 'Chocolate Cake?', 'Onion Rings?',
       'Side Salad#?', 'Grilled Vegetables#?', 'Iced Tea#?', 'Beef Chili#?',
       'Brownie#?', 'Iced Tea#', 'Lemonade#?', 'Chocolate Cake#?',
       'Pasta Alfredo#?', 'Cheesecake#', 'Mashed Potatoes#?'],
      dtype='object', name='Item')

In [ ]:
df.Item=df.Item.str.replace(r'[^A-Za-z ]','',regex=True)

In [ ]:
df.Item.value_counts().index

Index(['Chocolate Cake', 'Ice Cream', 'Side Salad', 'Mashed Potatoes',
       'Pasta Alfredo', 'Water ', 'French Fries', 'Grilled Chicken',
       'Coca Cola', 'Cheese Fries', 'Steak', 'Orange Juice',
       'Grilled Vegetables', 'Cheesecake', 'Lemonade', 'Sweet Potato Fries',
       'Beef Chili', 'Brownie', 'Chicken Melt', 'Fruit Salad', 'Salmon',
       'Vegetarian Platter', 'Garlic Bread', 'Iced Tea', 'Onion Rings',
       'Nachos Grande', 'Water', 'Lemonade '],
      dtype='object', name='Item')

In [ ]:
df

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60.0,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90.0,2022-07-20,Digital Wallet
...,...,...,...,...,...,...,...,...,...
17527,ORD_223096,CUST_088,Side Dishes,Garlic Bread,4.0,3,12.0,2022-04-06,Credit Card
17528,ORD_721774,CUST_006,Side Dishes,Mashed Potatoes,4.0,5,20.0,2022-04-22,Digital Wallet
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2,8.0,2022-01-27,Digital Wallet

#**Maʼlumotlarni filtrlash va qayta ishlash**

#9) Manfiy narx yoki 0 ga teng narx qiymatlarini toping va ularni qanday oʻzgartirish kerakligini hal qiling.

In [ ]:
#javobni shu yerda yozing
# barcha nan qimatlarga 3-masalada javob berib ketdim
# price ustunidagi -1 qiymatlarni esa category bo`yicha to`ldirdim

In [ ]:
df[df.Price.isnull()]

Empty DataFrame
Columns: [Order ID, Customer ID, Category, Item, Price, Quantity, Order Total, Order Date, Payment Method]
Index: []

In [ ]:
df[df.Price<=0]

Empty DataFrame
Columns: [Order ID, Customer ID, Category, Item, Price, Quantity, Order Total, Order Date, Payment Method]
Index: []

#10) Boʻsh toifalar (kategoriya) mavjudligini tekshiring va toʻgʻri kategoriya berish strategiyasini ishlab chiqing.

In [ ]:
#javobni shu yerda yozing
# bu masalaga ham 3-masalda javob berib ketdim
# categoriya ustunidagi nan qiymatlarni price ustuni bo`yicha to`ldirib ketdim

In [ ]:
df[df.Category.isnull()]

Empty DataFrame
Columns: [Order ID, Customer ID, Category, Item, Price, Quantity, Order Total, Order Date, Payment Method]
Index: []

#11) Bir xil, lekin turlicha yozilgan qiymatlar (Coffee, cofee, COFEE) mavjudligini tekshiring va tuzating.

In [ ]:
df.head()

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60.0,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90.0,2022-07-20,Digital Wallet

In [ ]:
#javobni shu yerda yozing
df.Category.unique()

array(['Side Dishes', 'Main Dishes', 'Desserts', 'Starters', 'Drinks'],
      dtype=object)

In [ ]:
df.Item.unique()

array(['Side Salad', 'Mashed Potatoes', 'Grilled Chicken',
       'Pasta Alfredo', 'Salmon', 'Garlic Bread', 'Chocolate Cake',
       'Vegetarian Platter', 'Brownie', 'Sweet Potato Fries', 'Lemonade',
       'Orange Juice', 'Coca Cola', 'Grilled Vegetables', 'Cheese Fries',
       'Beef Chili', 'Chicken Melt', 'Fruit Salad', 'French Fries',
       'Ice Cream', 'Cheesecake', 'Iced Tea', 'Water ', 'Nachos Grande',
       'Water', 'Onion Rings', 'Steak', 'Lemonade '], dtype=object)

In [ ]:
df['Payment Method'].unique()

array(['Credit Card', 'Digital Wallet', 'Cash'], dtype=object)

#12) `Customer ID` yoki boshqa identifikatorlarning takrorlanishini tekshiring.

In [ ]:
df['Customer ID'].duplicated().sum()

np.int64(16980)

In [ ]:
#javobni shu yerda yozing
df['Customer ID'][df['Customer ID'].duplicated()].unique()

array(['CUST_031', 'CUST_021', 'CUST_071', 'CUST_055', 'CUST_052',
       'CUST_040', 'CUST_008', 'CUST_057', 'CUST_094', 'CUST_090',
       'CUST_007', 'CUST_085', 'CUST_034', 'CUST_042', 'CUST_020',
       'CUST_024', 'CUST_096', 'CUST_041', 'CUST_036', 'CUST_066',
       'CUST_060', 'CUST_080', 'CUST_029', 'CUST_045', 'CUST_056',
       'CUST_038', 'CUST_068', 'CUST_093', 'CUST_013', 'CUST_082',
       'CUST_037', 'CUST_070', 'CUST_050', 'CUST_026', 'CUST_089',
       'CUST_074', 'CUST_058', 'CUST_011', 'CUST_054', 'CUST_097',
       'CUST_028', 'CUST_049', 'CUST_061', 'CUST_099', 'CUST_067',
       'CUST_017', 'CUST_051', 'CUST_053', 'CUST_004', 'CUST_043',
       'CUST_081', 'CUST_019', 'CUST_023', 'CUST_001', 'CUST_083',
       'CUST_002', 'CUST_033', 'CUST_062', 'CUST_063', 'CUST_092',
       'CUST_076', 'CUST_088', 'CUST_095', 'CUST_075', 'CUST_079',
       'CUST_048', 'CUST_091', 'CUST_018', 'CUST_077', 'CUST_059',
       'CUST_010', 'CUST_027', 'CUST_100', 'CUST_025', 'CUST_064',
       'CUST_084', 'CUST_047', 'CUST_022', 'CUST_072', 'CUST_009',
       'CUST_073', 'CUST_005', 'CUST_044', 'CUST_078', 'CUST_030',
       'CUST_006', 'CUST_014', 'CUST_003', 'CUST_098', 'CUST_035',
       'CUST_086', 'CUST_015', 'CUST_065', 'CUST_012', 'CUST_032',
       'CUST_069', 'CUST_016', 'CUST_087', 'CUST_039', 'CUST_046'],
      dtype=object)

In [ ]:
df['Order ID'].duplicated().sum()

np.int64(0)

#13) Mahsulotning ortiqcha taʼriflarini olib tashlang (Water (0.5), Water (1.0), Water → faqat Water qoldirish).

In [ ]:
#javobni shu yerda yozing
# buni 8-mashqda olib tashladim
df.Item.unique()

array(['Side Salad', 'Mashed Potatoes', 'Grilled Chicken',
       'Pasta Alfredo', 'Salmon', 'Garlic Bread', 'Chocolate Cake',
       'Vegetarian Platter', 'Brownie', 'Sweet Potato Fries', 'Lemonade',
       'Orange Juice', 'Coca Cola', 'Grilled Vegetables', 'Cheese Fries',
       'Beef Chili', 'Chicken Melt', 'Fruit Salad', 'French Fries',
       'Ice Cream', 'Cheesecake', 'Iced Tea', 'Water ', 'Nachos Grande',
       'Water', 'Onion Rings', 'Steak', 'Lemonade '], dtype=object)

#**Qayta ishlangan maʼlumotlar bilan tahlil**

#14) Eng koʻp sotilgan 5 ta mahsulotni aniqlang.

In [ ]:
df.head()

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60.0,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90.0,2022-07-20,Digital Wallet

In [ ]:
#javobni shu yerda yozing
most=df.groupby('Item')['Quantity'].sum().sort_values(ascending=False)
most.head(5)

Item
Chocolate Cake     3598
Ice Cream          3432
Side Salad         3345
Pasta Alfredo      3290
Mashed Potatoes    3231
Name: Quantity, dtype: int64

#15) Har bir mijoz oʻrtacha qancha pul sarflaganini hisoblang.

In [ ]:
#javobni shu yerda yozing
df.groupby('Customer ID')['Order Total'].mean()

Customer ID
CUST_001    17.585714
CUST_002    19.316860
CUST_003    17.364780
CUST_004    19.091716
CUST_005    17.461290
              ...
CUST_096    18.783854
CUST_097    19.766484
CUST_098    19.571023
CUST_099    20.821875
CUST_100    18.686224
Name: Order Total, Length: 100, dtype: float64

#16) Mijozlarning qaysi kunlarda koʻproq xarid qilgani bo‘yicha tahlil qiling.

In [ ]:
df.head()

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60.0,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90.0,2022-07-20,Digital Wallet

In [ ]:
df['Order Date']=pd.to_datetime(df['Order Date'])

In [ ]:
df['Order Date'].info()

<class 'pandas.core.series.Series'>
Index: 17080 entries, 0 to 17532
Series name: Order Date
Non-Null Count  Dtype
--------------  -----
17080 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 782.9 KB

In [ ]:
#javobni shu yerda yozing
df.groupby(df['Order Date'].dt.date)['Customer ID'].count().sort_values(ascending=False)

Order Date
2023-11-25    42
2023-08-22    40
2022-03-31    39
2022-04-02    39
2023-08-17    36
              ..
2022-07-07    13
2023-02-15    13
2023-08-27    12
2023-04-22    12
2023-01-16    11
Name: Customer ID, Length: 730, dtype: int64

#17) Narxi oʻrtacha narxdan ikki barobar yuqori boʻlgan mahsulotlarni toping.

In [ ]:
#javobni shu yerda yozing
mean=df.Price.mean().round()
df[df.Price>=mean*2]['Item'].value_counts()

Item
Grilled Chicken       822
Steak                 597
Salmon                445
Vegetarian Platter    403
Name: count, dtype: int64

#18) Mahsulotlar kategoriyalari bo‘yicha tahlil qiling va eng ko‘p sotiladigan kategoriyalarni aniqlang.

In [ ]:
#javobni shu yerda yozing
df.Category.value_counts()

Category
Starters       3493
Desserts       3485
Side Dishes    3474
Main Dishes    3326
Drinks         3302
Name: count, dtype: int64

#19) Har bir mijozning oʻrtacha xarid miqdorini (`groupby("customer_id")`) hisoblang.

In [ ]:
#javobni shu yerda yozing
df.groupby('Customer ID')['Order Total'].mean()

Customer ID
CUST_001    17.585714
CUST_002    19.316860
CUST_003    17.364780
CUST_004    19.091716
CUST_005    17.461290
              ...
CUST_096    18.783854
CUST_097    19.766484
CUST_098    19.571023
CUST_099    20.821875
CUST_100    18.686224
Name: Order Total, Length: 100, dtype: float64

In [ ]:
df.head()

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60.0,2023-09-27,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90.0,2022-07-20,Digital Wallet

#20) Qanday omillar sotuv hajmiga ta’sir qiladi? Bu bo‘yicha umumiy xulosa chiqaring. Javobni quyida kommentariya sifatida yozing!

In [ ]:
#javobni shu yerda yozing
# mahsulot kategoriyasi ,uning narhi va chegirmalar va uning qanchali ko`p (quantity)
# sotilayotgani.